### PR TITLE
Moved Generalised Headtracker component from Core

### PR DESCRIPTION
**Pull request by ExtremelySunnyYK**
This PR moves over the Generalised HeadTracker components from core `common/types` repo to the chainlink-relay repo. This allows chain specific repositories to make use of the generalised Headtracker interfaces.

**Changes**
- Moved over files from common/types. Moved over necessary utils and tests as well.
- Added mock files

**Note:**
- The tests will be on chain specific repository. For instance test for evm headtracker will be on `chainlink-core`, and test for Solana will be on `chainlink-solana`.
- This PR is an updated version of the previous PR attempt to migrate ht components. https://github.com/smartcontractkit/chainlink-relay/pull/123
- The code is being tested here by [Solana](https://github.com/smartcontractkit/chainlink-solana/pull/521) using components from `chainlink-relay` and all tests passes. 

Future work:
- Research to automate PR creation when there are changes on `core/common` and run chain specific tests of chainlink-relay headtracker

[Ticket](https://smartcontract-it.atlassian.net/browse/BCI-1287)

### CODE REVIEW

**Comment by jmank88** [comment]
@ExtremelySunnyYK 
Do you feel that this code is tested sufficiently when isolated in this repo? Or are we still depending on integration tests in the core repo for complete coverage?

**Comment by jmank88** [comment]
> The tests will be on chain specific folder. For instance EVM will have their own test for evm specific implementation, and Non-Evm will have their own test on their chain specific folder.

What do you mean by 'folder'? We will at least need _module_ separation to prevent the imports from polluting core, and the current policy is to avoid all chain-specific imports in this _repo_.

**Review by jmank88 — APPROVED** [review]
Tentatively blocking to asses whether we need to wait to be sure that CI is in a good place (tests/linter/sonar/etc.) before merging. Feel free to dismiss this if it looks healthy, or if the code is literally copied without changes.
cc @chudilka1

**Review by jmank88 — CHANGES_REQUESTED** [review]
Tentatively blocking to asses whether we need to wait to be sure that CI is in a good place (tests/linter/sonar/etc.) before merging. Feel free to dismiss this if CI looks healthy and comprehensive, or if the code is literally copied without changes.
cc @chudilka1

**Comment by ExtremelySunnyYK** [comment]
> > The tests will be on chain specific folder. For instance EVM will have their own test for evm specific implementation, and Non-Evm will have their own test on their chain specific folder.
> 
> What do you mean by 'folder'? We will at least need _module_ separation to prevent the imports from polluting core, and the current policy is to avoid all chain-specific imports in this _repo_.

@jmank88 sorry for the lack of clarity.  By folder I meant chain specific repository. 

For instance test for evm headtracker will be on `chainlink-core`, and test for Solana will be on `chainlink-solana`

Will update the PR description for clarity.

**Comment by ExtremelySunnyYK** [comment]
> @ExtremelySunnyYK 
> Do you feel that this code is tested sufficiently when isolated in this repo? Or are we still depending on integration tests in the core repo for complete coverage?

Thanks for bringing this up @jmank88 . We will still be having to depend on integration tests in the core / `chainlink-<chain>` repository for integration test for coverage. 

Curious if there might be a better approach?

@aalu1418 has also suggested how we can make use of GitHub automated PR in the meantime before completely moving from `core/common` to `chainlink-relay`. 
This helps to keep chainlink-relay updated of changes in core so that they remain the same.

**Pull request closed without merging**
